create extension if not exists pgcrypto;

create table if not exists admin_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text not null,
  role text not null default 'admin' check (role in ('admin')),
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  internal_code text,
  status text not null default 'draft' check (status in ('draft','active','reserved','sold','rented','hidden','archived')),
  show_on_website boolean not null default false,
  offer_type text not null default 'sale' check (offer_type in ('sale','rent')),
  property_type text not null default 'apartment' check (property_type in ('apartment','house','land','commercial','other')),
  ownership_type text,
  layout text,
  location text,
  address text,
  city text,
  city_part text,
  district text,
  region text,
  postal_code text,
  street text,
  house_number text,
  orientation_number text,
  gps_lat numeric,
  gps_lng numeric,
  price numeric,
  price_note text,
  currency text not null default 'CZK',
  price_unit text,
  price_negotiation boolean not null default false,
  usable_area numeric,
  floor_area numeric,
  land_area numeric,
  built_area numeric,
  floor integer,
  floors_total integer,
  condition text,
  building_type text,
  energy_class text,
  object_type text,
  object_kind text,
  object_location text,
  advert_subtype text,
  advert_room_count text,
  sale_date date,
  first_tour_date date,
  first_tour_date_to date,
  exclusivity boolean not null default false,
  elevator text,
  furnished text,
  balcony boolean not null default false,
  balcony_area numeric,
  loggia boolean not null default false,
  loggia_area numeric,
  terrace boolean not null default false,
  terrace_area numeric,
  cellar boolean not null default false,
  cellar_area numeric,
  garage boolean not null default false,
  garage_count integer,
  parking_lots integer,
  parking boolean not null default false,
  garden_area numeric,
  basin boolean not null default false,
  basin_area numeric,
  description_short text,
  description_long text,
  advert_price_text_note text,
  available_from date,
  ready_date date,
  contact_name text,
  contact_phone text,
  contact_email text,
  seller_id text,
  seller_rkid text,
  locality_inaccuracy_level integer not null default 2,
  export_to_sreality boolean not null default false,
  sreality_advert_id text,
  sreality_advert_rkid text,
  sreality_status text not null default 'not_exported' check (sreality_status in ('not_exported','dry_run_ready','pending','exported','update_needed','photo_sync_needed','error','removed')),
  sreality_published_status text,
  sreality_advert_url text,
  sreality_hash_id text,
  sreality_last_export_at timestamptz,
  sreality_last_update_at timestamptz,
  sreality_last_photo_sync_at timestamptz,
  sreality_error text,
  sreality_payload_preview jsonb,
  sreality_response_log jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  sold_at timestamptz,
  rented_at timestamptz,
  archived_at timestamptz
);

create table if not exists property_images (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references properties(id) on delete cascade,
  url text not null,
  storage_path text,
  alt text,
  sort_order integer not null default 0,
  is_main boolean not null default false,
  sreality_photo_id text,
  sreality_photo_rkid text,
  sreality_photo_kind integer,
  sreality_room_type integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sreality_export_logs (
  id uuid primary key default gen_random_uuid(),
  property_id uuid references properties(id) on delete set null,
  action text not null check (action in ('validate','dry_run','export_advert','update_advert','remove_advert','add_photo','delete_photo','sync_photos','list_adverts')),
  status text not null,
  request_payload jsonb,
  response_payload jsonb,
  status_code integer,
  status_message text,
  error_message text,
  performed_by uuid references admin_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists properties_public_idx on properties(status, show_on_website);
create index if not exists properties_slug_idx on properties(slug);
create index if not exists property_images_property_order_idx on property_images(property_id, sort_order);
create index if not exists sreality_logs_property_idx on sreality_export_logs(property_id, created_at desc);

insert into storage.buckets (id, name, public)
values ('property-images', 'property-images', true)
on conflict (id) do nothing;
